// At build time, this file would be generated by Discraft
// It would be updated during dev too when needed
// It would import all the events and register them with the client in a way that aligned with the adapters
// For example if the Vercel adapter was used, it would just warn that Vercel doesn't support events
// Extensions can also warn if they're incompatible with an adapter
// For an example of how it was done in the old version, view these files:
// /home/bestcodes/Documents/Code/The-Best-Codes/discraft-js/main/templates/ts/.discraft/events/index.ts
