// At build time, this file would be generated by Discraft
// It would be updated during dev too when needed
// It would import all the commands and register them with the client in a way that aligned with the adapters
// For example if the Vercel adapter was used, it would modify the logic to be an interaction endpoint, otherwise it would register and listen for commands like normal
// Extensions can also warn if they're incompatible with an adapter
// For an example of how it was done in the old version, view these files:
// /home/bestcodes/Documents/Code/The-Best-Codes/discraft-js/main/templates/ts/.discraft/commands/index.ts
// All files in this directory: /home/bestcodes/Documents/Code/The-Best-Codes/discraft-js/main/templates/vercel-ts-ai/.discraft/commands
